#include <vector>
#include "TGraphAsymmErrors.h"
void make_compare_plot_phd(){
  string period = "sk4";
  string type[] = {"p_epi","p_mupi","p_eee","p_eee_final","p_muee",//4
    "p_muee_final","p_eemu_final","p_emumu","p_emumu_final","p_mumue_final",//9
    "p_mumumu","p_mumumu_final","fcmc_final","fcmc_real","fcdt_final"};

  gROOT->SetStyle("Plain");
  gStyle->SetOptStat(0);
  gStyle->SetPadLeftMargin(0.12);
  vector<string> hist,save_name,hist_title,xtitle,ytitle,comment;
  vector<vector<string>> hist_set,hist_title_set,comment_set;
  vector<vector<int>> input_type_set,mode_type_set,color_set,style_set;
  vector<vector<float>> scale_set;
  vector<int> normalize,dology,input_type,add_ratio,mode_type,use_validation,rebin,color,add_error,style;
  vector<float> xmax,xmin,ymax,ymin,xcomment,ycomment,legxmin,legymin,legxmax,legymax,step,scale;
  hist.clear();hist_set.clear();normalize.clear();dology.clear();input_type.clear();rebin.clear();save_name.clear();
  input_type_set.clear();add_ratio.clear();mode_type_set.clear();mode_type.clear();use_validation.clear();scale.clear();
  color_set.clear();color.clear();xmax.clear();xmin.clear();ymax.clear();ymin.clear();hist_title_set.clear();hist_title.clear();
  xtitle.clear();ytitle.clear();comment_set.clear();comment.clear();xcomment.clear();ycomment.clear();style_set.clear();style.clear();
  legxmin.clear();legymin.clear();legxmax.clear();legymax.clear();add_error.clear();step.clear();scale_set.clear();

  hist.push_back("mom_proton_reco_cut5_nring0_mulike0_michel3");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(10);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mom_proton_reco_cut5_nring0_mulike0_michel3");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(2);style.push_back(1);scale.push_back(0.005);
  hist.push_back("mom_proton_reco_cut5_nring0_mulike0_michel3_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(4);style.push_back(2);scale.push_back(0.005);
  save_name.push_back("hist_phd/compare_total_mom_sig_bkg_p_mumumu_sk4.pdf");
  xtitle.push_back("Total momentum [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 #mu-like");
  comment.push_back("2 pr 3 decay electron");
  xcomment.push_back(600);ycomment.push_back(4.8);
  step.push_back(0.3);
  ymin.push_back(0);ymax.push_back(5);xmin.push_back(0);xmax.push_back(1000);
  legxmin.push_back(0.4);legymin.push_back(0.4);legxmax.push_back(0.75);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mass_proton_reco_cut5_nring0_mulike0_michel3");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(10);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mass_proton_reco_cut5_nring0_mulike0_michel3");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(2);style.push_back(1);scale.push_back(0.002);
  hist.push_back("mass_proton_reco_cut5_nring0_mulike0_michel3_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(4);style.push_back(2);scale.push_back(0.002);
  save_name.push_back("hist_phd/compare_total_mass_sig_bkg_p_mumumu_sk4.pdf");
  xtitle.push_back("Total mass [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 #mu-like");
  comment.push_back("2 or 3 decay electron");
  xcomment.push_back(100);ycomment.push_back(4.8);
  step.push_back(0.3);
  ymin.push_back(0);ymax.push_back(5);xmin.push_back(0);xmax.push_back(1250);
  legxmin.push_back(0.15);legymin.push_back(0.35);legxmax.push_back(0.5);legymax.push_back(0.65);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  /*hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(7);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(2);style.push_back(1);scale.push_back(0.01);
  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(4);style.push_back(2);scale.push_back(0.01);
  save_name.push_back("hist_phd/compare_total_mom_sig_bkg_p_emumu_sk4.pdf");
  xtitle.push_back("Total momentum [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("1 e-like & 2 #mu-like");
  comment.push_back("2 decay electron");
  xcomment.push_back(700);ycomment.push_back(9);
  step.push_back(0.5);
  ymin.push_back(0);ymax.push_back(10);xmin.push_back(0);xmax.push_back(1000);
  legxmin.push_back(0.4);legymin.push_back(0.35);legxmax.push_back(0.75);legymax.push_back(0.65);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(7);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(2);style.push_back(1);scale.push_back(0.004);
  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(4);style.push_back(2);scale.push_back(0.004);
  save_name.push_back("hist_phd/compare_total_mass_sig_bkg_p_emumu_sk4.pdf");
  xtitle.push_back("Total mass [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("1 e-like & 2 #mu-like");
  comment.push_back("2 decay electron");
  xcomment.push_back(100);ycomment.push_back(9);
  step.push_back(0.5);
  ymin.push_back(0);ymax.push_back(10);xmin.push_back(0);xmax.push_back(1250);
  legxmin.push_back(0.15);legymin.push_back(0.35);legxmax.push_back(0.5);legymax.push_back(0.65);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(4);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(2);style.push_back(1);scale.push_back(0.01);
  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(4);style.push_back(2);scale.push_back(0.01);
  save_name.push_back("hist_phd/compare_total_mom_sig_bkg_p_muee_sk4.pdf");
  xtitle.push_back("Total momentum [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("1 #mu-like & 2 e-like");
  comment.push_back("1 decay electron");
  comment.push_back("#pi^{0} veto");
  xcomment.push_back(700);ycomment.push_back(14);
  step.push_back(1);
  ymin.push_back(0);ymax.push_back(15);xmin.push_back(0);xmax.push_back(1000);
  legxmin.push_back(0.4);legymin.push_back(0.35);legxmax.push_back(0.75);legymax.push_back(0.65);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(4);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(2);style.push_back(1);scale.push_back(0.005);
  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(4);style.push_back(2);scale.push_back(0.005);
  save_name.push_back("hist_phd/compare_total_mass_sig_bkg_p_muee_sk4.pdf");
  xtitle.push_back("Total mass [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("1 #mu-like & 2 e-like");
  comment.push_back("1 decay electron");
  comment.push_back("#pi^{0} veto");
  xcomment.push_back(100);ycomment.push_back(14);
  step.push_back(1);
  ymin.push_back(0);ymax.push_back(15);xmin.push_back(0);xmax.push_back(1250);
  legxmin.push_back(0.15);legymin.push_back(0.35);legxmax.push_back(0.5);legymax.push_back(0.65);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel0");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(2);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(2);style.push_back(1);scale.push_back(0.06);
  hist.push_back("mom_proton_reco_cut5_nring1_mulike0_michel0_fp1");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(4);style.push_back(2);scale.push_back(0.06);
  save_name.push_back("hist_phd/compare_total_mom_sig_bkg_p_eee_sk4.pdf");
  xtitle.push_back("Total momentum [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 e-like");
  comment.push_back("No decay electron");
  xcomment.push_back(700);ycomment.push_back(95);
  step.push_back(5);
  ymin.push_back(0);ymax.push_back(100);xmin.push_back(0);xmax.push_back(1000);
  legxmin.push_back(0.55);legymin.push_back(0.3);legxmax.push_back(0.9);legymax.push_back(0.6);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel0");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(2);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(2);style.push_back(1);scale.push_back(0.025);
  hist.push_back("mass_proton_reco_cut5_nring1_mulike0_michel0_fp1");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(4);style.push_back(2);scale.push_back(0.025);
  save_name.push_back("hist_phd/compare_total_mass_sig_bkg_p_eee_sk4.pdf");
  xtitle.push_back("Total mass [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 e-like");
  comment.push_back("No decay electron");
  xcomment.push_back(100);ycomment.push_back(95);
  step.push_back(5);
  ymin.push_back(0);ymax.push_back(100);xmin.push_back(0);xmax.push_back(1250);
  legxmin.push_back(0.15);legymin.push_back(0.35);legxmax.push_back(0.5);legymax.push_back(0.65);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(5);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("ntag_multiplicity_cut5_nring1_mulike0_michel0");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(2);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("ntag_multiplicity_cut5_nring1_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(2);style.push_back(1);scale.push_back(0.05);
  hist.push_back("ntag_multiplicity_cut5_nring1_mulike0_michel0_fp1");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(4);style.push_back(2);scale.push_back(0.05);
  save_name.push_back("hist_phd/compare_ntag_sig_bkg_p_eee_sk4.pdf");
  xtitle.push_back("Number of tagged neutron");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 e-like");
  comment.push_back("No decay electron");
  xcomment.push_back(7);ycomment.push_back(330);
  step.push_back(20);
  ymin.push_back(0);ymax.push_back(350);xmin.push_back(0);xmax.push_back(10);
  legxmin.push_back(0.45);legymin.push_back(0.3);legxmax.push_back(0.8);legymax.push_back(0.6);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("mass_pi0_reco_cut4_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(4);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("mass_pi0_reco_cut4_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(2);style.push_back(1);scale.push_back(0.1);
  hist.push_back("mass_pi0_reco_cut4_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(4);style.push_back(2);scale.push_back(0.1);
  save_name.push_back("hist_phd/compare_pi0_mass_sig_bkg_p_muee_sk4.pdf");
  xtitle.push_back("Mass of 2 e-like rings [MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("1 #mu-like & 2 e-like");
  comment.push_back("1 decay electron");
  xcomment.push_back(550);ycomment.push_back(48);
  step.push_back(3);
  ymin.push_back(0);ymax.push_back(50);xmin.push_back(0);xmax.push_back(800);
  legxmin.push_back(0.45);legymin.push_back(0.4);legxmax.push_back(0.8);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel0");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(2);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(2);style.push_back(1);scale.push_back(0.07);
  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel0_fp1");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(4);style.push_back(2);scale.push_back(0.07);
  save_name.push_back("hist_phd/compare_nDecayE_sig_bkg_p_eee_sk4.pdf");
  xtitle.push_back("Number of decay electrons");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 e-like");
  xcomment.push_back(4);ycomment.push_back(560);
  step.push_back(30);
  ymin.push_back(0);ymax.push_back(600);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.45);legymin.push_back(0.3);legxmax.push_back(0.8);legymax.push_back(0.6);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(4);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(2);style.push_back(1);scale.push_back(0.07);
  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(4);style.push_back(2);scale.push_back(0.07);
  save_name.push_back("hist_phd/compare_nDecayE_sig_bkg_p_muee_sk4.pdf");
  xtitle.push_back("Number of decay electrons");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("1 #mu-like & 2 e-like");
  xcomment.push_back(3.5);ycomment.push_back(470);
  step.push_back(30);
  ymin.push_back(0);ymax.push_back(500);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.5);legymin.push_back(0.3);legxmax.push_back(0.9);legymax.push_back(0.6);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(7);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(2);style.push_back(1);scale.push_back(0.04);
  hist.push_back("n_michel_electron_cut3_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(4);style.push_back(2);scale.push_back(0.04);
  save_name.push_back("hist_phd/compare_nDecayE_sig_bkg_p_emumu_sk4.pdf");
  xtitle.push_back("Number of decay electrons");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("2 #mu-like & 1 e-like");
  xcomment.push_back(3.5);ycomment.push_back(140);
  step.push_back(10);
  ymin.push_back(0);ymax.push_back(150);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.5);legymin.push_back(0.3);legxmax.push_back(0.9);legymax.push_back(0.6);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("n_michel_electron_cut3_nring0_mulike0_michel3");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(10);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("n_michel_electron_cut3_nring0_mulike0_michel3");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(2);style.push_back(1);scale.push_back(0.011);
  hist.push_back("n_michel_electron_cut3_nring0_mulike0_michel3_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(4);style.push_back(2);scale.push_back(0.011);
  save_name.push_back("hist_phd/compare_nDecayE_sig_bkg_p_mumumu_sk4.pdf");
  xtitle.push_back("Number of decay electrons");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  comment.push_back("3 #mu-like");
  xcomment.push_back(4.2);ycomment.push_back(28);
  step.push_back(2);
  ymin.push_back(0);ymax.push_back(30);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.15);legymin.push_back(0.4);legxmax.push_back(0.55);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("nElikeRing_angle_nring3_cut2_nring1_mulike0_michel0");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(2);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("nElikeRing_angle_nring3_cut2_nring1_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(2);style.push_back(1);scale.push_back(0.15);
  hist.push_back("nElikeRing_angle_nring3_cut2_nring1_mulike0_michel0_fp1");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(4);style.push_back(2);scale.push_back(0.15);
  save_name.push_back("hist_phd/compare_nElikeRing_sig_bkg_p_eee_sk4.pdf");
  xtitle.push_back("Number of e-like rings");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  xcomment.push_back(4.3);ycomment.push_back(1100);
  step.push_back(70);
  ymin.push_back(0);ymax.push_back(1200);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.15);legymin.push_back(0.62);legxmax.push_back(0.5);legymax.push_back(0.92);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("nMulikeRing_angle_nring3_cut2_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(4);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("nMulikeRing_angle_nring3_cut2_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(2);style.push_back(1);scale.push_back(0.2);
  hist.push_back("nMulikeRing_angle_nring3_cut2_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(4);style.push_back(2);scale.push_back(0.2);
  save_name.push_back("hist_phd/compare_nMulikeRing_sig_bkg_p_muee_sk4.pdf");
  xtitle.push_back("Number of #mu-like rings");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  xcomment.push_back(4.3);ycomment.push_back(1100);
  step.push_back(70);
  ymin.push_back(0);ymax.push_back(1200);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.5);legymin.push_back(0.4);legxmax.push_back(0.9);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("nMulikeRing_angle_nring3_cut2_nring1_mulike0_michel1");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(7);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("nMulikeRing_angle_nring3_cut2_nring1_mulike0_michel1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(2);style.push_back(1);scale.push_back(0.25);
  hist.push_back("nMulikeRing_angle_nring3_cut2_nring1_mulike0_michel1_fp1");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(8);mode_type.push_back(8);color.push_back(4);style.push_back(2);scale.push_back(0.25);
  save_name.push_back("hist_phd/compare_nMulikeRing_sig_bkg_p_emumu_sk4.pdf");
  xtitle.push_back("Number of #mu-like rings");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  xcomment.push_back(4.3);ycomment.push_back(1100);
  step.push_back(70);
  ymin.push_back(0);ymax.push_back(1200);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.15);legymin.push_back(0.4);legxmax.push_back(0.55);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("nMulikeRing_angle_nring3_cut2_nring0_mulike0_michel3");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(10);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("nMulikeRing_angle_nring3_cut2_nring0_mulike0_michel3");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(2);style.push_back(1);scale.push_back(0.3);
  hist.push_back("nMulikeRing_angle_nring3_cut2_nring0_mulike0_michel3_fp1");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}(free proton)");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(4);style.push_back(2);scale.push_back(0.3);
  save_name.push_back("hist_phd/compare_nMulikeRing_sig_bkg_p_mumumu_sk4.pdf");
  xtitle.push_back("Number of #mu-like rings");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("3 rings");
  xcomment.push_back(4.3);ycomment.push_back(1100);
  step.push_back(70);
  ymin.push_back(0);ymax.push_back(1200);xmin.push_back(0);xmax.push_back(4);
  legxmin.push_back(0.15);legymin.push_back(0.4);legxmax.push_back(0.55);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();scale.clear();

  hist.push_back("nRing_cut1_nring0_mulike0_michel0");
  hist_title.push_back("Background");
  input_type.push_back(13);mode_type.push_back(2);color.push_back(1);style.push_back(1);scale.push_back(1);
  hist.push_back("nRing_cut1_nring0_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(2);style.push_back(1);scale.push_back(2.5);
  hist.push_back("nRing_cut1_nring0_mulike0_michel0_fp1");
  hist_title.push_back("p#rightarrowe^{+}e^{+}e^{-}(free proton)");
  input_type.push_back(3);mode_type.push_back(3);color.push_back(4);style.push_back(2);scale.push_back(2.5);
  save_name.push_back("hist_phd/compare_nring_sig_bkg_p_eee_sk4.pdf");
  xtitle.push_back("Number of reconstructed rings");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  xcomment.push_back(6);ycomment.push_back(19000);
  step.push_back(1000);
  ymin.push_back(0);ymax.push_back(20000);xmin.push_back(0);xmax.push_back(6);
  legxmin.push_back(0.5);legymin.push_back(0.4);legxmax.push_back(0.9);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(0);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();

  hist.push_back("nRing_cut1_nring0_mulike0_michel0");
  hist_title.push_back("p#rightarrow#mu^{+}e^{+}e^{-}");
  input_type.push_back(5);mode_type.push_back(5);color.push_back(2);style.push_back(1);scale.push_back(1);
  hist.push_back("nRing_cut1_nring0_mulike0_michel0");
  hist_title.push_back("p#rightarrowe^{+}#mu^{+}#mu^{-}");
  input_type.push_back(7);mode_type.push_back(7);color.push_back(kGreen+2);style.push_back(1);scale.push_back(1);
  hist.push_back("nRing_cut1_nring0_mulike0_michel0");
  hist_title.push_back("p#rightarrow#mu^{+}#mu^{+}#mu^{-}");
  input_type.push_back(11);mode_type.push_back(11);color.push_back(4);style.push_back(1);scale.push_back(1);
  save_name.push_back("hist_phd/compare_nring_sig_p_muee_emumu_mumumu_sk4.pdf");
  xtitle.push_back("Number of reconstructed rings");
  ytitle.push_back("");
  comment.push_back("SK4");
  comment.push_back("Area normalized");
  xcomment.push_back(5);ycomment.push_back(0.75);
  step.push_back(0.05);
  ymin.push_back(0);ymax.push_back(0.8);xmin.push_back(0);xmax.push_back(6);
  legxmin.push_back(0.6);legymin.push_back(0.4);legxmax.push_back(0.8);legymax.push_back(0.7);
  add_ratio.push_back(0);add_error.push_back(0);normalize.push_back(1);use_validation.push_back(0);
  rebin.push_back(1);dology.push_back(0);
  hist_set.push_back(hist);hist_title_set.push_back(hist_title);input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);color_set.push_back(color);comment_set.push_back(comment);scale_set.push_back(scale);
  style_set.push_back(style);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();style.clear();
  */

  /*hist.push_back("true_min_mom_lepton_fp1");
  hist_title.push_back("Minimum");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(2);
  hist.push_back("true_mid_mom_lepton_fp1");
  hist_title.push_back("Middle");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(kGreen+2);
  hist.push_back("true_max_mom_lepton_fp1");
  hist_title.push_back("Maximum");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(4);
  save_name.push_back("hist_phd/compare_true_mom_electrons_p_eee.pdf");
  xtitle.push_back("True momentum[MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  comment.push_back("Free proton");
  xcomment.push_back(10);ycomment.push_back(240);
  step.push_back(15);
  ymin.push_back(0);ymax.push_back(250);xmin.push_back(0);xmax.push_back(500);
  legxmin.push_back(0.2);legymin.push_back(0.45);legxmax.push_back(0.5);legymax.push_back(0.75);
  add_ratio.push_back(0);
  add_error.push_back(0);
  scale.push_back(0);
  use_validation.push_back(1);
  rebin.push_back(1);
  dology.push_back(0);
  hist_set.push_back(hist);
  hist_title_set.push_back(hist_title);
  input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);
  color_set.push_back(color);
  comment_set.push_back(comment);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();

  hist.push_back("total_true_mass_free");
  hist_title.push_back("Free proton");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(1);
  hist.push_back("total_true_mass_sstate");
  hist_title.push_back("s-state");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(2);
  hist.push_back("total_true_mass_pstate");
  hist_title.push_back("p-state");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(kGreen+2);
  hist.push_back("total_true_mass_cor");
  hist_title.push_back("correlated decay");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(4);
  save_name.push_back("hist_phd/compare_total_true_mass_hstate.pdf");
  xtitle.push_back("True proton mass[MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  xcomment.push_back(10);ycomment.push_back(2000);
  step.push_back(800);
  ymin.push_back(1);ymax.push_back(3000);xmin.push_back(0);xmax.push_back(1000);
  legxmin.push_back(0.2);legymin.push_back(0.45);legxmax.push_back(0.5);legymax.push_back(0.75);
  add_ratio.push_back(0);
  add_error.push_back(0);
  scale.push_back(0);
  use_validation.push_back(1);
  rebin.push_back(1);
  dology.push_back(1);
  hist_set.push_back(hist);
  hist_title_set.push_back(hist_title);
  input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);
  color_set.push_back(color);
  comment_set.push_back(comment);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();

  hist.push_back("total_true_mom_free");
  hist_title.push_back("Free proton");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(1);
  hist.push_back("total_true_mom_sstate");
  hist_title.push_back("s-state");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(2);
  hist.push_back("total_true_mom_pstate");
  hist_title.push_back("p-state");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(kGreen+2);
  hist.push_back("total_true_mom_cor");
  hist_title.push_back("correlated decay");
  input_type.push_back(4);mode_type.push_back(4);color.push_back(4);
  save_name.push_back("hist_phd/compare_total_true_mom_hstate.pdf");
  xtitle.push_back("True proton momentum[MeV]");
  ytitle.push_back("Events");
  comment.push_back("SK4");
  comment.push_back("p#rightarrowe^{+}e^{+}e^{-}");
  xcomment.push_back(100);ycomment.push_back(2000);
  step.push_back(800);
  ymin.push_back(1);ymax.push_back(3000);xmin.push_back(0);xmax.push_back(800);
  legxmin.push_back(0.6);legymin.push_back(0.45);legxmax.push_back(0.9);legymax.push_back(0.75);
  add_ratio.push_back(0);
  add_error.push_back(0);
  scale.push_back(0);
  use_validation.push_back(1);
  rebin.push_back(1);
  dology.push_back(1);
  hist_set.push_back(hist);
  hist_title_set.push_back(hist_title);
  input_type_set.push_back(input_type);
  mode_type_set.push_back(mode_type);
  color_set.push_back(color);
  comment_set.push_back(comment);
  hist.clear();input_type.clear();mode_type.clear();color.clear();hist_title.clear();comment.clear();
  */

  TFile *input;
  TH1 *first_hist;
  for(int s=0;s<hist_set.size();s++){
    TCanvas *c = new TCanvas(Form("canvas%d",s),"",800,600);
    if(add_ratio[s]){
      TPad* p1 = new TPad("main","main",0.0,0.2,1.0,1.0,10,0,0);
      p1->SetNumber(1);
      p1->SetBottomMargin(0);
      p1->Draw();
      TPad* p2 = new TPad("ratio","ratio",0.0,0.0,1.0,0.2,10,0,0);
      p2->SetTopMargin(0);
      p2->SetBottomMargin(0.5);
      p2->SetNumber(2);
      p2->Draw();
    }
    if(dology[s]) c->SetLogy();
    TLegend *leg = new TLegend(legxmin[s],legymin[s],legxmax[s],legymax[s]);
    leg->SetFillStyle(0);
    leg->SetBorderSize(0);
    for(int h=0;h<hist_set[s].size();h++){
      if(use_validation[s]) input = TFile::Open(Form("../output/%s.%s.mode_%s_validation.root",type[input_type_set[s].at(h)].c_str(),period.c_str(),type[mode_type_set[s].at(h)].c_str()));
      else input = TFile::Open(Form("../output/%s.%s.mode_%s.root",type[input_type_set[s].at(h)].c_str(),period.c_str(),type[mode_type_set[s].at(h)].c_str()));
      TH1* this_hist = (TH1*) input->Get(hist_set[s].at(h).c_str());
      this_hist->Rebin(rebin[s]);
      //cout << "scale is " << scale_set[s].at(h) << endl;
      this_hist->Scale(scale_set[s].at(h));
      if(normalize[s] && this_hist->GetEntries()) this_hist->Scale(1./this_hist->Integral());
      this_hist->SetLineWidth(2);
      this_hist->SetLineColor(color_set[s].at(h));
      this_hist->SetLineStyle(style_set[s].at(h));
      leg->AddEntry(this_hist,hist_title_set[s].at(h).c_str(),"l");
      if(add_ratio[s]) c->cd(1);
      if(h==0){
        this_hist->GetYaxis()->SetRangeUser(ymin[s],ymax[s]);
        this_hist->GetXaxis()->SetRangeUser(xmin[s],xmax[s]);
        this_hist->GetXaxis()->SetTitle(xtitle[s].c_str());
        this_hist->GetYaxis()->SetTitle(ytitle[s].c_str());
        this_hist->GetYaxis()->SetTitleOffset(1.5);
        if(add_error[s]) this_hist->Draw("hist E0");
        else this_hist->Draw("hist");
        first_hist = this_hist;
      }
      else{
        if(add_error[s]) this_hist->Draw("same hist E0");
        else this_hist->Draw("same hist");
        TH1 *ratio_hist = (TH1*) this_hist->Clone("ratio_plot");
        ratio_hist->Divide(first_hist);
        if(add_ratio[s]){
          c->cd(2);
          if(h==1){
            TH1* frame;
            frame=gPad->DrawFrame(xmin[s], 0.5, xmax[s], 1.5);
            frame->GetYaxis()->SetLabelSize(0.1);
            frame->GetXaxis()->SetLabelSize(0.2);
          }
          ratio_hist->Draw("same");
          TLine *line = new TLine(xmin[s],1,xmax[s],1);
          line->SetLineStyle(2);
          line->Draw();
          TLine *line2 = new TLine(xmin[s],2,xmax[s],2);
          line2->SetLineStyle(2);
          line2->Draw();
        }
      }
    }
    leg->Draw();
    TLatex *text = new TLatex();
    text->SetTextSize(0.04);
    for(int t=0;t<comment_set[s].size();t++){
      //cout << comment_set[s].at(t) << endl;
      text->DrawLatex(xcomment[s],ycomment[s]-step[s]*t,comment_set[s].at(t).c_str());
    }
    c->SaveAs(save_name[s].c_str());

  }

}
